title: AWS Services & Cloud Engineering Blog
description: In-depth guides and best practices for AWS services
author: Shaheryar Khalid

url: "https://sheheriyar99.github.io"
baseurl: ""

theme: minima

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

permalink: /blog/:year/:month/:day/:title/

# Blog config
excerpt_separator: "<!--more-->"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: "<!--more-->"
